services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: pnpm run start:dev api
    env_file:
      - ./apps/api/.env
    ports:
      - '1111:1111'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
