services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: pnpm run start:dev api
    env_file:
      - ./apps/api/.env.development
    ports:
      - '1111:1111'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env.development
    ports:
      - '2222:2222'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq

  patient:
    build:
      context: .
      dockerfile: ./apps/patient/Dockerfile
      target: development
    command: pnpm run start:dev patient
    env_file:
      - ./apps/patient/.env.development
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13.4-management-alpine
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env.development
